spring:
  application:
    name: grow
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/grow}
    username: ${DATASOURCE_USER:root}
    password: ${DATASOURCE_PWD:}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloudinary:
  cloud-name: whwnnsyd
  api-key: 855813416484976
  api-secret: dcNP2mLcjPDMavbd9oH8S2RdffE